import daisyui from "daisyui";

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      fontFamily: {
        display: ["Syne", "ui-sans-serif", "system-ui", "sans-serif"],
        serif: ['"Source Serif 4"', "Georgia", "serif"],
        sans: ["Syne", "ui-sans-serif", "system-ui", "sans-serif"],
      },
      letterSpacing: {
        kicker: "0.22em",
      },
      maxWidth: {
        page: "72rem",
      },
      transitionDuration: {
        theme: "280ms",
      },
    },
  },
  plugins: [daisyui],
  daisyui: {
    logs: false,
    themes: [
      {
        nightfall: {
          primary: "#c084fc",
          "primary-content": "#1a1025",
          secondary: "#e9d5ff",
          "secondary-content": "#1a1025",
          accent: "#a855f7",
          "accent-content": "#f8f0ff",
          neutral: "#2a2833",
          "neutral-content": "#f3eee6",
          "base-100": "#0c0b10",
          "base-200": "#15141c",
          "base-300": "#22212c",
          "base-content": "#f3eee6",
          info: "#7dd3fc",
          success: "#86efac",
          warning: "#fde68a",
          error: "#fca5a5",
          "--rounded-box": "0.35rem",
          "--rounded-btn": "0.2rem",
          "--rounded-badge": "0.2rem",
          "--animation-btn": "0.18s",
          "--btn-text-case": "none",
          "--border-btn": "1px",
          "--tab-radius": "0.2rem",
        },
      },
      {
        lumen: {
          primary: "#6b21a8",
          "primary-content": "#f8f0ff",
          secondary: "#5b21b6",
          "secondary-content": "#f8f0ff",
          accent: "#7c3aed",
          "accent-content": "#f8f0ff",
          neutral: "#2e2a36",
          "neutral-content": "#fcfaf6",
          "base-100": "#fcfaf6",
          "base-200": "#f3eee6",
          "base-300": "#e6ded2",
          "base-content": "#16141c",
          info: "#0369a1",
          success: "#166534",
          warning: "#854d0e",
          error: "#9f1239",
          "--rounded-box": "0.35rem",
          "--rounded-btn": "0.2rem",
          "--rounded-badge": "0.2rem",
          "--animation-btn": "0.18s",
          "--btn-text-case": "none",
          "--border-btn": "1px",
          "--tab-radius": "0.2rem",
        },
      },
      {
        folio: {
          primary: "#5c2a5a",
          "primary-content": "#f8f1e6",
          secondary: "#3f2a1d",
          "secondary-content": "#f8f1e6",
          accent: "#7a3e6e",
          "accent-content": "#f8f1e6",
          neutral: "#2a2118",
          "neutral-content": "#f3ebda",
          "base-100": "#f3ebda",
          "base-200": "#e8dcc4",
          "base-300": "#d9c9a8",
          "base-content": "#1c140e",
          info: "#1e4d6b",
          success: "#2f5d3a",
          warning: "#8a5a12",
          error: "#8a2b2b",
          "--rounded-box": "0.35rem",
          "--rounded-btn": "0.2rem",
          "--rounded-badge": "0.2rem",
          "--animation-btn": "0.18s",
          "--btn-text-case": "none",
          "--border-btn": "1px",
          "--tab-radius": "0.2rem",
        },
      },
      {
        contrast: {
          primary: "#e9d5ff",
          "primary-content": "#000000",
          secondary: "#ffffff",
          "secondary-content": "#000000",
          accent: "#ffffff",
          "accent-content": "#000000",
          neutral: "#1a1a1a",
          "neutral-content": "#ffffff",
          "base-100": "#000000",
          "base-200": "#0a0a0a",
          "base-300": "#1a1a1a",
          "base-content": "#ffffff",
          info: "#7dd3fc",
          success: "#86efac",
          warning: "#fde68a",
          error: "#fca5a5",
          "--rounded-box": "0.2rem",
          "--rounded-btn": "0.15rem",
          "--rounded-badge": "0.15rem",
          "--animation-btn": "0.12s",
          "--btn-text-case": "none",
          "--border-btn": "1px",
          "--tab-radius": "0.15rem",
        },
      },
    ],
  },
}
